### ISSUE TITLE
Details about the eq19

### ISSUE THREAD

**Issue by hjxwhy** [pals-ttic/sjc#14]
Thanks for your work. 
I am curious about the eq19 in the paper, can you provide a more detailed derivation or some material? Thanks!

**Comment by w-hc** [comment]
Thanks for your interest in the work. 
The following wikipedia pages might be helpful. 
https://en.wikipedia.org/wiki/Sum_of_normally_distributed_random_variables
https://en.wikipedia.org/wiki/List_of_convolutions_of_probability_distributions

**Comment by hjxwhy** [comment]
Thanks, I got it!
