### ISSUE TITLE
About bs=1 and the use of the Monte-Carlo estimate

### ISSUE THREAD

**Issue by j0seo** [pals-ttic/sjc#15]
Hello! Thank you for sharing your great work.

 In the paper, it says "An additional contribution of ours beyond DreamFusion [41] is our analysis of the effect that the OOD problem has when using a denoiser on rendered images (Claim 1), and the PAAS method to address it. For the variance reduction technique, namely the use of the Monte-Carlo estimate ˆ on Eq. (16), or − (in DreamFusion), vs. on Eq. (15), we observe comparable performance between the two methods empirically for 3D generation." 

But in the code, it seems that only one noise is created (bs=1). If I understand correctly, to perturb multiple random noises and average them, the variable 'bs' should be more than one.  I'm curious if I understand it well. Thanks!

**Comment by w-hc** [comment]
In practice setting it to a higher number incurs a lot more compute, cuz the bottleneck is the 2d model. It seemed more economical to do more 3d updates that way.

**Comment by j0seo** [comment]
Thanks for the quick response! Have you tried experimenting with increasing 'bs'? I'm curious if the quality improves even though more computation is needed.

**Comment by w-hc** [comment]
There doesn't seem to be a significant difference.

**Comment by j0seo** [comment]
Thank you!
