### ISSUE TITLE
question of the provement of the formula17

### ISSUE THREAD

**Issue by qzp2018** [pals-ttic/sjc#16]
As far as I personally understand，the formula 17 comes from the formula18 by derivation，while the inequality in formula 18 establish，but it doesn‘t means that the inequality still establish after derivation.Would you please explain this question?

**Comment by w-hc** [comment]
Thanks for ur interest in the work. Could u elaborate a bit more?

**Comment by qzp2018** [comment]
Thank you for your reply.For example,though f(x)>g(x),but it doesn't means that f'(x)>g'(x).So though the formula 18 is true,but it doesn't means that the unequal sign still holds after the derivation about x(the formula 24 does this job)，which proves the claim1 and  leads to the formula 17.

**Comment by w-hc** [comment]
I think that claim 1 is ok; we compute a gradient on the lower bound, and by improving the lower bound the quantity itself is improved. 

If you mean that the $\approx$ here in 17 is used too loosely, I agree. $f(x) > g(x)$ doesn't really say much about $f'(x)$ and $g'(x)$. So using the $\approx$ is not good, and we see that on some synthetic experiments that gradients are in fact very different. 

So it's probably better to focus on Lemma 1 and Claim 1. Those statements are tighter. (Also in Lemma 1 we don't really rely on the assumption of empirical data distribution; that needs a change too).
