### ISSUE TITLE
Question about train_eye_with_prompts

### ISSUE THREAD

**Issue by woo1726** [pals-ttic/sjc#17]
It might be a dumb question but I'm new to 3D. I'm trying to understand the purpose of **φ = np.arccos(1 - 2 * (vs / π))** in **pose.py**. As far as I know, **φ** is the increased version of **vs** if **vs** is lower than π/2, and decreased one if  **vs** is greater than π/2.  I would really appreciate it if you could tell me the purpose of that line!
Great work by the way!

**Comment by w-hc** [comment]
It is intended to generate uniformly sampled points on a sphere. 
This blog post might help: http://corysimon.github.io/articles/uniformdistn-on-sphere/

**Comment by w-hc** [comment]
It shifts the density sightly towards the belt. You can plot it and see. 
<img width="562" alt="arccos plot" src="https://user-images.githubusercontent.com/17956191/220441592-465d3325-f1ea-4ce4-8255-9c63123807b6.png">

**Comment by woo1726** [comment]
thanks a lot!!
