### ISSUE TITLE
Query : 4 channels in nerf output

### ISSUE THREAD

**Issue by aradhyamathur** [pals-ttic/sjc#25]
Hi, I have a query pertaining to the voxnerf implementation, the features generated 4 channels, whereas the density feature is computed separately, does the last channel correspond to alpha ?

**Comment by aradhyamathur** [comment]
I wanted to test with vanilla nerf implementation like stable diffusion, the outputs there are 3 channel, so wanted to know what change could be made for the same.

**Comment by w-hc** [comment]
The four channels are for the latent features of Stable Diffusion. It’s not RGBa. The density is controlled by another small 1-channel voxel.

**Comment by aradhyamathur** [comment]
Oh I see, so it's essentially predicting the latents which are then denoised by the SD network to produce the RGB while density is predicted from the other module. Is that correct ?

**Comment by w-hc** [comment]
That’s right.

**Comment by aradhyamathur** [comment]
Thanks for the clarification.
