### ISSUE TITLE
question about formula

### ISSUE THREAD

**Issue by dlg-dlg** [pals-ttic/sjc#29]
hello, i have a question about the code for score calculation:
in the paper:
grad=(Ds-y)/chosen_σs**2
but in the code:
grad=(Ds-y)/chosen_σs
look forward to your reply, thank you

**Comment by dlg-dlg** [comment]
got it

**Comment by fkcptlst** [comment]
> got it

Hi, I have a similar question. Could you please explain a little? Thanks!

**Comment by fkcptlst** [comment]
Now I see. #6
