### ISSUE TITLE
3D Reconstruction?

### ISSUE THREAD

**Issue by AmanKishore** [pals-ttic/sjc#3]
Hi this is great work! 
Since Sparsefusion's code is not out yet what do you recommend for 3D Reconstruction? PixelNerf?

Thanks!

**Comment by duxiaodan** [comment]
Hi I'm glad you like our work. In this work we do generation and we use our self-implemented voxel NeRF. Based on my understanding of SparseFusion's setup, any NeRF-like model such as Instant NGP should work

**Comment by AmanKishore** [comment]
Great thank you!

**Comment by AmanKishore** [comment]
@duxiaodan what's the best way to save the nerf that you are rendering with voxel NeRF?

**Comment by duxiaodan** [comment]
The code will save the voxel to a .pt file
